<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exercises = [
            ['name' => 'Shoulder Shrug', 'description' => 'Raise shoulders toward ears', 'difficulty_level' => '1', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Sit straight and raise shoulders toward ears and hold for 3 seconds'],
            ['name' => 'Hand and Wrist Stretch', 'description' => 'Stretch hand and wrist', 'difficulty_level' => '1', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Place palms together and push left hand against right and hold for 3 seconds'],
            ['name' => 'Seated Marching', 'description' => 'Lift knees alternately while sitting', 'difficulty_level' => '2', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 15, 'instructions' => 'While seated lift one knee as if marching and hold for 2 seconds'],
            ['name' => 'Towel Slide', 'description' => 'Slide towel on table', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Place towel under hand on table and slide forward and back with control'],
            ['name' => 'Sit-to-Stand', 'description' => 'Rise from sitting to standing', 'difficulty_level' => '3', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 10, 'instructions' => 'Rise from a seated position to standing using even weight on both legs'],
            ['name' => 'Finger Tapping', 'description' => 'Tap fingers against thumb', 'difficulty_level' => '3', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Tap each finger against the thumb in a sequence from index to pinky'],
            ['name' => 'Wall Push-ups', 'description' => 'Push against wall', 'difficulty_level' => '3', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 8, 'instructions' => 'Stand facing wall and place palms on wall and lean in and push away'],
            ['name' => 'Squeeze Ball', 'description' => 'Squeeze therapy ball', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Hold ball in affected hand and squeeze as hard as possible for 5 seconds'],
            ['name' => 'Heel-to-Toe Stand', 'description' => 'Stand in tandem position', 'difficulty_level' => '4', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Stand with one foot directly in front of the other in tandem and hold balance'],
            ['name' => 'Single Leg Stance', 'description' => 'Stand on one leg', 'difficulty_level' => '5', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Lift one leg and stand on the other and hold for as long as possible'],
            ['name' => 'Facial Muscle Exercises', 'description' => 'Exercise facial muscles', 'difficulty_level' => '1', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Smile widely and hold for 3 seconds. Purse lips and hold for 3 seconds. Raise eyebrows and hold for 3 seconds'],
            ['name' => 'Cheek Puffing', 'description' => 'Puff out cheeks', 'difficulty_level' => '1', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Puff out cheeks and hold for 3 seconds then release slowly'],
            ['name' => 'Tongue Exercises', 'description' => 'Move tongue exercises', 'difficulty_level' => '2', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Stick tongue out and hold for 3 seconds. Move tongue side to side slowly'],
            ['name' => 'Lip Rounding', 'description' => 'Round lips exercise', 'difficulty_level' => '1', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Round lips as if saying O and hold for 3 seconds. Then stretch lips as if saying E'],
            ['name' => 'Speech Repetition', 'description' => 'Repeat words slowly', 'difficulty_level' => '2', 'target_area' => 'face', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Repeat simple words slowly ba-ba-ba pa-pa-pa ta-ta-ta for 1 minute each'],
            ['name' => 'Counting Exercise', 'description' => 'Count aloud slowly', 'difficulty_level' => '2', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 3, 'instructions' => 'Count from 1 to 10 slowly and clearly and repeat 3 times'],
            ['name' => 'Swallowing Exercise', 'description' => 'Practice swallowing', 'difficulty_level' => '2', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Swallow saliva slowly and deliberately and practice dry swallows 5 times'],
            ['name' => 'Neck Stretches', 'description' => 'Stretch neck muscles', 'difficulty_level' => '1', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Gently tilt head toward each shoulder and hold for 15 seconds each side'],
            ['name' => 'Eye Tracking', 'description' => 'Track moving objects with eyes', 'difficulty_level' => '2', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Follow a moving object with eyes only without head movement in all directions'],
            ['name' => 'Visual Scanning', 'description' => 'Scan room systematically', 'difficulty_level' => '2', 'target_area' => 'face', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Scan room systematically from left to right and identify objects'],
            ['name' => 'Attention Focus', 'description' => 'Focus on single object', 'difficulty_level' => '2', 'target_area' => 'cognitive', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Focus on a single object for 1 minute without distraction and increase duration gradually'],
            ['name' => 'Memory Recall', 'description' => 'Recall items from list', 'difficulty_level' => '2', 'target_area' => 'cognitive', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Recall 5 items from a list after 1 minute and gradually increase number of items'],
            ['name' => 'Puzzle Solving', 'description' => 'Complete puzzles', 'difficulty_level' => '3', 'target_area' => 'cognitive', 'duration_minutes' => 20, 'repetitions' => 1, 'instructions' => 'Complete simple jigsaw puzzles or word searches appropriate to ability level'],
            ['name' => 'Reading Exercise', 'description' => 'Read aloud passages', 'difficulty_level' => '2', 'target_area' => 'cognitive', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Read aloud simple sentences or short passages and focus on comprehension'],
            ['name' => 'Emotional Expression', 'description' => 'Practice emotional expression', 'difficulty_level' => '2', 'target_area' => 'emotional', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Practice expressing emotions through facial expressions and controlled breathing'],
            ['name' => 'Deep Breathing', 'description' => 'Practice deep breathing', 'difficulty_level' => '1', 'target_area' => 'emotional', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Inhale slowly for 4 counts and hold for 4 counts and exhale for 4 counts'],
            ['name' => 'Relaxation Technique', 'description' => 'Progressive muscle relaxation', 'difficulty_level' => '1', 'target_area' => 'emotional', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Tense and release muscle groups progressively from toes to head'],
            ['name' => 'Guided Imagery', 'description' => 'Visualize calm scenes', 'difficulty_level' => '2', 'target_area' => 'emotional', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Visualize calm peaceful scenes while practicing slow breathing'],
            ['name' => 'Knee Lifts', 'description' => 'Lift knees toward chest', 'difficulty_level' => '2', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Sit in chair and lift one knee up toward chest and hold for 2 seconds and lower slowly'],
            ['name' => 'Heel Slides', 'description' => 'Slide heels on bed', 'difficulty_level' => '2', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Lie on back and slide heel toward buttock and hold for 2 seconds and slide back'],
            ['name' => 'Glute Squeezes', 'description' => 'Squeeze buttock muscles', 'difficulty_level' => '2', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Squeeze buttock muscles and hold for 5 seconds and release'],
            ['name' => 'Calf Raises', 'description' => 'Raise up on toes', 'difficulty_level' => '3', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Stand facing counter and rise up on toes and hold for 2 seconds and lower down'],
            ['name' => 'Step-Ups', 'description' => 'Step up onto low step', 'difficulty_level' => '3', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 8, 'instructions' => 'Step up onto low step with one leg and step down and alternate legs'],
            ['name' => 'Tandem Walking', 'description' => 'Walk in straight line', 'difficulty_level' => '4', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Walk in straight line placing one foot directly in front of other'],
            ['name' => 'Sit and Reach', 'description' => 'Reach toward toes', 'difficulty_level' => '2', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Sit in chair and reach toward toes and hold for 15 seconds and return to start'],
            ['name' => 'Hip Flexor Stretch', 'description' => 'Stretch hip flexors', 'difficulty_level' => '2', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 5, 'instructions' => 'Sit in chair and pull one knee toward chest and hold for 15 seconds each leg'],
            ['name' => 'Arm Circles', 'description' => 'Make circles with arms', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Extend arms out to sides and make small circles forward for 30 seconds and reverse'],
            ['name' => 'Bicep Curls', 'description' => 'Curl weights toward shoulders', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Hold weight and bend elbow bringing weight toward shoulder and lower slowly'],
            ['name' => 'Tricep Extensions', 'description' => 'Extend arms overhead', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Hold weight overhead and bend elbow lowering weight behind head and extend back up'],
            ['name' => 'Wrist Flexion', 'description' => 'Bend wrist upward', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Hold weight with palm up and bend wrist upward and lower slowly'],
            ['name' => 'Pronation Supination', 'description' => 'Rotate forearm', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Hold weight with arm bent and rotate forearm palm up then palm down'],
            ['name' => 'Shoulder Abduction', 'description' => 'Raise arms to sides', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Hold weights at sides and raise arms out to sides to shoulder height and lower'],
            ['name' => 'Shoulder Flexion', 'description' => 'Raise arms forward', 'difficulty_level' => '2', 'target_area' => 'upper_limb', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Hold weights at sides and raise arms forward to shoulder height and lower slowly'],
            ['name' => 'Seated Marching Advanced', 'description' => 'Advanced seated marching', 'difficulty_level' => '3', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 20, 'instructions' => 'Sit in chair and lift knees alternately higher than basic version and maintain rhythm'],
            ['name' => 'Standing Balance', 'description' => 'Stand without support', 'difficulty_level' => '3', 'target_area' => 'lower_limb', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Stand with feet hip-width apart and maintain balance without holding counter'],
            ['name' => 'Gait Training', 'description' => 'Walk with assistive device', 'difficulty_level' => '3', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Walk with assistive device focusing on even weight distribution and smooth gait'],
            ['name' => 'Stair Training', 'description' => 'Practice stairs', 'difficulty_level' => '4', 'target_area' => 'lower_limb', 'duration_minutes' => 15, 'repetitions' => 1, 'instructions' => 'Practice going up and down stairs with handrail and one step at a time'],
            ['name' => 'Coordination Drill', 'description' => 'Touch nose and finger', 'difficulty_level' => '3', 'target_area' => 'coordination', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Touch nose with finger and then touch examiners finger at arms length and alternate'],
            ['name' => 'Rapid Alternating', 'description' => 'Tap knees alternately', 'difficulty_level' => '3', 'target_area' => 'coordination', 'duration_minutes' => 10, 'repetitions' => 1, 'instructions' => 'Tap knees alternately with hands as quickly as possible while maintaining control'],
            ['name' => 'Cross Body Reach', 'description' => 'Reach across body', 'difficulty_level' => '3', 'target_area' => 'coordination', 'duration_minutes' => 10, 'repetitions' => 10, 'instructions' => 'Reach right hand across body to touch left shoulder and alternate sides'],
        ];

        foreach ($exercises as $exercise) {
            Exercise::create($exercise);
        }
    }
}
